# Домашнее задание. Линейная алгебра и библиотека NumPy
В этом домашнем задании вам предстоит самостоятельно реализовать линейно-алгебраические операции с помощью чистого Python, а затем попрактиковаться в использовании уже готовых реализаций из numpy. Кроме того, вы сравните время работы вашей реализации с реализацией из библиотеки NumPy и убедитесь, что скорость работы "коробочных" реализаций выше.

In [1]:
import numpy as np
import random
import scipy.stats as sps

ModuleNotFoundError: No module named 'scipy'

## Задание 1
Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

<class 'numpy.ndarray'> [0.25517625 0.34595235 0.36132484]


In [ ]:
def no_numpy_scalar(v1, v2):
    """
    v1: list[n] --- первый вектор-аргумент длиной n
    v2: list[n] --- второй вектор-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов v1 и v2

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению v1 и v2

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """
    result = #YOUR CODE
    return result

In [ ]:
def numpy_scalar(v1, v2):
    """
    v1: np.array[n] --- первый вектор-аргумент длиной n
    v2: np.array[n] --- второй вектор-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов v1 и v2

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """
    result = #YOUR CODE
    return result

In [ ]:
%time product_1 = no_numpy_scalar(a,b)
%time product_2 = numpy_scalar(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

## Задание 2
Вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета `numpy` и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.395839   0.21379428 0.07247983 ... 0.64980615 0.64291476 0.32526086]
 [0.99447693 0.63253878 0.10648252 ... 0.09038331 0.08219018 0.63331995]
 [0.03470463 0.83264811 0.00266264 ... 0.41459466 0.20456353 0.88582864]
 ...
 [0.6902504  0.10926463 0.64770747 ... 0.7091193  0.19629277 0.9975028 ]
 [0.64204202 0.65320852 0.35489944 ... 0.00704072 0.78367391 0.59237454]
 [0.84137914 0.89991396 0.55261748 ... 0.3186097  0.48761123 0.91937383]]
[[0.19223844 0.02409304 0.41697875 ... 0.2896223  0.03328157 0.64914984]
 [0.59910385 0.40862453 0.40050159 ... 0.89650084 0.46264964 0.90442002]
 [0.87800265 0.28263125 0.82332552 ... 0.71561631 0.51356527 0.58747008]
 ...
 [0.83887046 0.24098338 0.29652699 ... 0.75683419 0.17818834 0.37654114]
 [0.26376756 0.33976523 0.95381248 ... 0.8179511  0.18956817 0.70542156]
 [0.02341907 0.56668502 0.53320765 ... 0.52531754 0.27821011 0.91949749]]


In [ ]:
def no_numpy_mult(a, b):
    """
    A: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    B: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return C: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: A и B размерностью size x size
    Возвращает матрицу их произведения A * B = C

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    pass

In [ ]:
def numpy_mult(a, b):
    """
    A: np.array[size, size]              --- первая матрица-аргумент
    B: np.array[size, size]              --- вторая матрица-аргумент
    return C: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц A и B

    Функция принимает на вход две матрицы: A и B размерностью size x size
    Возвращает матрицу их произведения A * B = C

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    pass

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

In [ ]:
# проверим корректность
assert np.allclose(np.array(M1), M2)